craziNES: nes::MMU Class Reference
nes::MMU Class Reference
#include <memory.h>
Public Member Functions
uint8_t read_byte (uint16_t addr)
void write_byte (uint16_t addr, uint8_t value)
void load_rom (std::string filename)
Private Member Functions
memory_section get_section (uint16_t addr)
Static Private Member Functions
static void ppu_write (MMU *mmu, memory_section s)
Private Attributes
uint8_t * ram = new uint8_t[0x800]
uint8_t * ppu_registers = new uint8_t[0x8]
uint8_t * registers = new uint8_t[0x20]
uint8_t * lprgrom = new uint8_t[0x4000]
uint8_t * hprgrom = new uint8_t[0x4000]
uint8_t mapper = 0
nes::ROM * rom = nullptr
Detailed Description
Definition at line 20 of file memory.h.
Member Function Documentation
get_section()
memory_section nes::MMU::get_section (uint16_t addr) private
Definition at line 8 of file memory.cpp.
References nes::memory_section::addr, nes::memory_section::offset, ppu_registers, ppu_write(), nes::memory_section::ptr, ram, registers, and nes::memory_section::write_handler.
Referenced by read_byte(), and write_byte().
     {
         memory_section s;
         if((addr >= 0) && (addr <= 0x1FFF))
         {
             s.addr = addr % 0x800;
             s.offset = 0x0;
             s.ptr = ram;
             return s;
         }
         if((addr >= 0x2000) && (addr <= 0x3FFF))
         {
             s.addr = ((addr - 0x2000) % 0x8) + 0x2000;
             s.offset = 0x2000;
             s.ptr = ppu_registers;
             s.write_handler = &ppu_write;
             return s;
         }
         if((addr >= 0x4000) && (addr <= 0x401F))
         {
             s.addr = addr;
             s.offset = 0x4000;
             s.ptr = registers;
             return s;
         }
         char message[1024];
         sprintf(message, "Unknown memory address 0x%.4X", addr);
         throw std::string(message);
     }
load_rom()
void nes::MMU::load_rom (std::string filename)
Definition at line 93 of file memory.cpp.
References nes::NES_header::flag6, nes::NES_header::flag7, nes::ROM::get_header(), mapper, and rom.
Referenced by MainWindow::MainWindow().
     {
         try
         {
             rom = new nes::ROM(filename);
         }
         catch(std::string e)
         {
             throw e;
         }
         NES_header header = rom->get_header();
         mapper = header.flag7 & 0xF0;
         mapper += header.flag6 >> 4;
     }
ppu_write()
void nes::MMU::ppu_write (MMU * mmu, memory_section s) static private
Definition at line 86 of file memory.cpp.
References nes::memory_section::addr, and read_byte().
Referenced by get_section().
     {
         char message[1024];
         sprintf(message, "Wrote 0x%X to 0x%X", mmu->read_byte(s.addr), s.addr);
         throw std::string(message);
     }
read_byte()
uint8_t nes::MMU::read_byte (uint16_t addr)
Definition at line 42 of file memory.cpp.
References nes::memory_section::addr, get_section(), nes::memory_section::offset, and nes::memory_section::ptr.
Referenced by ppu_write().
     {
         memory_section s;
         try
         {
             s = get_section(addr);
         }
         catch(std::string e)
         {
             throw e;
         }
         uint8_t *p = (uint8_t *)s.ptr;
         return p[s.addr - s.offset];
     }
write_byte()
void nes::MMU::write_byte (uint16_t addr, uint8_t value)
Definition at line 59 of file memory.cpp.
References nes::memory_section::addr, get_section(), nes::memory_section::offset, nes::memory_section::ptr, and nes::memory_section::write_handler.
     {
         memory_section s;
         try
         {
             s = get_section(addr);
         }
         catch(std::string e)
         {
             throw e;
         }
         uint8_t *p = (uint8_t *)s.ptr;
         p[s.addr - s.offset] = value;
         if(s.write_handler == nullptr) return ;
         try
         {
             s.write_handler(this, s);
         }
         catch(std::string e)
         {
             throw e;
         }
     }
Member Data Documentation
hprgrom
uint8_t* nes::MMU::hprgrom = new uint8_t[0x4000] private
Definition at line 33 of file memory.h.
lprgrom
uint8_t* nes::MMU::lprgrom = new uint8_t[0x4000] private
Definition at line 32 of file memory.h.
mapper
uint8_t nes::MMU::mapper = 0 private
Definition at line 34 of file memory.h.
Referenced by load_rom().
ppu_registers
uint8_t* nes::MMU::ppu_registers = new uint8_t[0x8] private
Definition at line 30 of file memory.h.
Referenced by get_section().
ram
uint8_t* nes::MMU::ram = new uint8_t[0x800] private
Definition at line 29 of file memory.h.
Referenced by get_section().
registers
uint8_t* nes::MMU::registers = new uint8_t[0x20] private
Definition at line 31 of file memory.h.
Referenced by get_section().
rom
nes::ROM* nes::MMU::rom = nullptr private
Definition at line 35 of file memory.h.
Referenced by load_rom().
The documentation for this class was generated from the following files:
include/memory.h
src/memory.cpp