craziNES: nes::cpu_6502 Class Reference
nes::cpu_6502 Class Reference
#include <cpu_6502.h>
Public Member Functions
cpu_6502 ()
uint16_t get_PC ()
uint8_t get_A ()
std::string get_state ()
uint8_t get_status ()
uint32_t get_cycles ()
std::string step ()
void load_rom (std::string filename)
void nmi ()
Public Attributes
Mapper * mapper
Private Member Functions
void push8 (uint8_t value)
uint8_t pop8 ()
void push16 (uint16_t value)
uint16_t pop16 ()
void setN (uint8_t check)
bool checkN ()
void setV (uint8_t check)
void clearV ()
bool checkV ()
void setZ (uint8_t check)
bool checkZ ()
void setC ()
void clearC ()
bool checkC ()
void setI ()
void clearI ()
void setD ()
void clearD ()
Static Private Member Functions
static void not_implemented (cpu_6502 *, opcode_t *)
static void brk (cpu_6502 *cpu, opcode_t *op)
static void slo_zp (cpu_6502 *, opcode_t *)
static void php (cpu_6502 *cpu, opcode_t *op)
static void ora_imm (cpu_6502 *cpu, opcode_t *op)
static void slo_abs (cpu_6502 *cpu, opcode_t *op)
static void bpl (cpu_6502 *cpu, opcode_t *op)
static void clc (cpu_6502 *cpu, opcode_t *op)
static void jsr (cpu_6502 *cpu, opcode_t *op)
static void and_ind_x (cpu_6502 *cpu, opcode_t *op)
static void bit_zp (cpu_6502 *cpu, opcode_t *op)
static void plp (cpu_6502 *cpu, opcode_t *op)
static void and_imm (cpu_6502 *cpu, opcode_t *op)
static void bmi (cpu_6502 *cpu, opcode_t *op)
static void rla_zp_x (cpu_6502 *, opcode_t *)
static void sec (cpu_6502 *cpu, opcode_t *op)
static void rti (cpu_6502 *cpu, opcode_t *op)
static void pha (cpu_6502 *cpu, opcode_t *op)
static void eor_imm (cpu_6502 *cpu, opcode_t *op)
static void jmp_abs (cpu_6502 *cpu, opcode_t *op)
static void bvc (cpu_6502 *cpu, opcode_t *op)
static void cli (cpu_6502 *, opcode_t *op)
static void rts (cpu_6502 *cpu, opcode_t *op)
static void pla (cpu_6502 *cpu, opcode_t *op)
static void adc_imm (cpu_6502 *cpu, opcode_t *op)
static void bvs (cpu_6502 *cpu, opcode_t *op)
static void sei (cpu_6502 *cpu, opcode_t *op)
static void sta_zp (cpu_6502 *cpu, opcode_t *op)
static void stx_zp (cpu_6502 *cpu, opcode_t *op)
static void dey (cpu_6502 *, opcode_t *)
static void sta_abs (cpu_6502 *cpu, opcode_t *op)
static void stx_abs (cpu_6502 *cpu, opcode_t *op)
static void bcc (cpu_6502 *cpu, opcode_t *op)
static void sta_ind_y (cpu_6502 *, opcode_t *op)
static void txs (cpu_6502 *cpu, opcode_t *op)
static void ldy_imm (cpu_6502 *cpu, opcode_t *op)
static void ldx_imm (cpu_6502 *cpu, opcode_t *op)
static void lda_zp (cpu_6502 *, opcode_t *)
static void ldx_zp (cpu_6502 *, opcode_t *)
static void lda_imm (cpu_6502 *cpu, opcode_t *op)
static void lda_abs (cpu_6502 *cpu, opcode_t *op)
static void bcs (cpu_6502 *cpu, opcode_t *op)
static void lda_zp_x (cpu_6502 *cpu, opcode_t *op)
static void clv (cpu_6502 *cpu, opcode_t *op)
static void lda_abs_x (cpu_6502 *, opcode_t *)
static void cpy_imm (cpu_6502 *cpu, opcode_t *op)
static void dec_zp (cpu_6502 *cpu, opcode_t *op)
static void cmp_imm (cpu_6502 *cpu, opcode_t *op)
static void dex (cpu_6502 *cpu, opcode_t *op)
static void dec_abs (cpu_6502 *cpu, opcode_t *op)
static void bne (cpu_6502 *cpu, opcode_t *op)
static void cld (cpu_6502 *cpu, opcode_t *op)
static void cpx_imm (cpu_6502 *cpu, opcode_t *op)
static void nop_ea (cpu_6502 *cpu, opcode_t *op)
static void sbc_imm (cpu_6502 *, opcode_t *)
static void beq (cpu_6502 *cpu, opcode_t *op)
static void nop_zp_F4 (cpu_6502 *, opcode_t *)
static void sed (cpu_6502 *, opcode_t *)
Private Attributes
nes::ROM * rom = nullptr
nes::NES_header header
PPU * ppu = nullptr
uint8_t A = 0
uint8_t X = 0
uint8_t Y = 0
uint8_t status = 0x24
uint8_t SP = 0xFD
uint16_t PC = 0
uint32_t cycles = 0
uint32_t last_cycles = 0
void(* opcode [0x100])(cpu_6502 *, opcode_t *)
Detailed Description
Definition at line 32 of file cpu_6502.h.
Constructor & Destructor Documentation
cpu_6502()
nes::cpu_6502::cpu_6502 ()
Definition at line 842 of file cpu_6502.cpp.
References ADC_imm, adc_imm(), AND_imm, and_imm(), AND_ind_x, and_ind_x(), BCC, bcc(), BCS, bcs(), beq(), BEQ, BIT_zp, bit_zp(), BMI, bmi(), bne(), BNE, BPL, bpl(), BRK, brk(), BVC, bvc(), BVS, bvs(), CLC, clc(), cld(), CLD, CLI, cli(), CLV, clv(), cmp_imm(), CMP_imm, cpx_imm(), CPX_imm, CPY_imm, cpy_imm(), dec_abs(), DEC_abs, dec_zp(), DEC_zp, dex(), DEX, DEY, dey(), EOR_imm, eor_imm(), JMP_abs, jmp_abs(), JSR, jsr(), LDA_abs, lda_abs(), LDA_abs_x, lda_abs_x(), LDA_imm, lda_imm(), LDA_zp, lda_zp(), LDA_zp_x, lda_zp_x(), LDX_imm, ldx_imm(), LDX_zp, ldx_zp(), LDY_imm, ldy_imm(), nop_ea(), NOP_EA, nop_zp_F4(), NOP_zp_F4, not_implemented(), opcode, ORA_imm, ora_imm(), PHA, pha(), PHP, php(), PLA, pla(), PLP, plp(), ppu, RTI, rti(), RTS, rts(), sbc_imm(), SBC_imm, SEC, sec(), sed(), SED, SEI, sei(), SLO_abs, slo_abs(), SLO_zp, slo_zp(), STA_abs, sta_abs(), STA_ind_y, sta_ind_y(), STA_zp, sta_zp(), STX_abs, stx_abs(), STX_zp, stx_zp(), TXS, and txs().
     {
         this->ppu = new nes::PPU(this);
         uint16_t counter = 0;
         while(counter < 256)
         {
             opcode[counter] = not_implemented;
             counter++;
         }
         opcode[BRK] = brk;
         opcode[SLO_zp] = slo_zp;
         opcode[PHP] = php;
         opcode[ORA_imm] = ora_imm;
         opcode[SLO_abs] = slo_abs;
         opcode[BPL] = bpl;
         opcode[CLC] = clc;
         opcode[JSR] = jsr;
         opcode[AND_ind_x] = and_ind_x;
         opcode[BIT_zp] = bit_zp;
         opcode[PLP] = plp;
         opcode[AND_imm] = and_imm;
         opcode[BMI] = bmi;
         opcode[SEC] = sec;
         opcode[RTI] = rti;
         opcode[PHA] = pha;
         opcode[EOR_imm] = eor_imm;
         opcode[JMP_abs] = jmp_abs;
         opcode[BVC] = bvc;
         opcode[CLI] = cli;
         opcode[RTS] = rts;
         opcode[PLA] = pla;
         opcode[ADC_imm] = adc_imm;
         opcode[BVS] = bvs;
         opcode[SEI] = sei;
         opcode[STA_zp] = sta_zp;
         opcode[STX_zp] = stx_zp;
         opcode[DEY] = dey;
         opcode[STA_abs] = sta_abs;
         opcode[STX_abs] = stx_abs;
         opcode[BCC] = bcc;
         opcode[STA_ind_y] = sta_ind_y;
         opcode[TXS] = txs;
         opcode[LDY_imm] = ldy_imm;
         opcode[LDX_imm] = ldx_imm;
         opcode[LDA_zp] = lda_zp;
         opcode[LDX_zp] = ldx_zp;
         opcode[LDA_imm] = lda_imm;
         opcode[LDA_abs] = lda_abs;
         opcode[BCS] = bcs;
         opcode[LDA_zp_x] = lda_zp_x;
         opcode[CLV] = clv;
         opcode[LDA_abs_x] = lda_abs_x;
         opcode[CPY_imm] = cpy_imm;
         opcode[DEC_zp] = dec_zp;
         opcode[CMP_imm] = cmp_imm;
         opcode[DEX] = dex;
         opcode[DEC_abs] = dec_abs;
         opcode[BNE] = bne;
         opcode[CLD] = cld;
         opcode[SBC_imm] = sbc_imm;
         opcode[CPX_imm] = cpx_imm;
         opcode[NOP_EA] = nop_ea;
         opcode[BEQ] = beq;
         opcode[NOP_zp_F4] = nop_zp_F4;
         opcode[SED] = sed;
     }
Member Function Documentation
adc_imm()
void nes::cpu_6502::adc_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 441 of file cpu_6502.cpp.
References A, checkC(), clearC(), cycles, nes::opcode_t::imm, PC, setC(), setN(), setV(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x69
         uint16_t temp = cpu->A + op->imm + cpu->checkC();
         uint8_t v = ~(cpu->A ^ op->imm) & (cpu->A ^ temp) & 0x80 ? 0xFF : 0x00;
         cpu->setV(v);
         cpu->clearC();
         if(temp > 0xFF) cpu->setC();
         cpu->A = temp & 0xFF;
         cpu->setZ(cpu->A);
         cpu->setN(temp);
         cpu->PC += op->sz;
         cpu->cycles += 2;
     }
and_imm()
void nes::cpu_6502::and_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 310 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, PC, setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x29
         cpu->A &= op->imm;
         cpu->cycles += 2;
         cpu->PC += op->sz;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
     }
and_ind_x()
void nes::cpu_6502::and_ind_x (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 269 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0x21
         uint16_t addr = (0 << 8) | ((op->imm + cpu->X) & 0xFF);
         uint16_t t_addr = (cpu->mapper->read_byte(addr + 1) << 8) |
                           cpu->mapper->read_byte(addr);
         uint8_t value = cpu->mapper->read_byte(t_addr);
         cpu->A &= value;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 6;
     }
bcc()
void nes::cpu_6502::bcc (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 529 of file cpu_6502.cpp.
References checkC(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x90
         if(!cpu->checkC())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
bcs()
void nes::cpu_6502::bcs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 633 of file cpu_6502.cpp.
References checkC(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xB0
         if(cpu->checkC())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
beq()
void nes::cpu_6502::beq (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 810 of file cpu_6502.cpp.
References checkZ(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xF0
         if(cpu->checkZ())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
bit_zp()
void nes::cpu_6502::bit_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 285 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setV(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x24
         uint16_t addr = (0 << 8) | op->imm;
         uint8_t acc = cpu->A;
         uint8_t test = cpu->mapper->read_byte(addr);
         cpu->setZ(acc & test);
         cpu->setN(test);
         cpu->setV(test);
         cpu->PC += op->sz;
         cpu->cycles += 3;
     }
bmi()
void nes::cpu_6502::bmi (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 320 of file cpu_6502.cpp.
References checkN(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x30
         if(cpu->checkN())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
bne()
void nes::cpu_6502::bne (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 745 of file cpu_6502.cpp.
References checkZ(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xD0
         if(!cpu->checkZ())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
bpl()
void nes::cpu_6502::bpl (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 232 of file cpu_6502.cpp.
References checkN(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x10
         if(!cpu->checkN())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + (int8_t)(op->imm);
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
brk()
void nes::cpu_6502::brk (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 152 of file cpu_6502.cpp.
References cycles, mapper, PC, push8(), nes::Mapper::read_byte(), setI(), status, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x00
         cpu->cycles += 7;
         cpu->PC += op->sz;
         cpu->push8(cpu->PC >> 8);
         cpu->push8(cpu->PC & 0xFF);
         uint8_t status = cpu->status;
         status |= 0x10;
         status |= 0x20;
         cpu->push8(status);
         uint8_t pcl = cpu->mapper->read_byte(0xFFFE);
         cpu->setI();
         uint8_t pch = cpu->mapper->read_byte(0xFFFF);
         cpu->PC = (pch << 8) | pcl;
     }
bvc()
void nes::cpu_6502::bvc (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 396 of file cpu_6502.cpp.
References checkV(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x50
         if(!cpu->checkV())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
bvs()
void nes::cpu_6502::bvs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 459 of file cpu_6502.cpp.
References checkV(), cycles, nes::opcode_t::imm, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x70
         if(cpu->checkV())
         {
             uint16_t next_addr = cpu->PC + op->sz;
             cpu->PC += op->sz + op->imm;
             cpu->cycles += 3;
             if((next_addr >> 8) != (cpu->PC >> 8)) cpu->cycles += 2;
         }
         else
         {
             cpu->PC += op->sz;
             cpu->cycles += 2;
         }
     }
checkC()
bool nes::cpu_6502::checkC () private
Definition at line 104 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), bcc(), bcs(), and sbc_imm().
     {
         return status & 0x1;
     }
checkN()
bool nes::cpu_6502::checkN () private
Definition at line 62 of file cpu_6502.cpp.
References status.
Referenced by bmi(), and bpl().
     {
         return (status >> 7) & 0x1;
     }
checkV()
bool nes::cpu_6502::checkV () private
Definition at line 78 of file cpu_6502.cpp.
References status.
Referenced by bvc(), and bvs().
     {
         return (status >> 6) & 0x1;
     }
checkZ()
bool nes::cpu_6502::checkZ () private
Definition at line 89 of file cpu_6502.cpp.
References status.
Referenced by beq(), and bne().
     {
         return status & 0x2;
     }
clc()
void nes::cpu_6502::clc (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 249 of file cpu_6502.cpp.
References clearC(), cycles, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x18
         cpu->clearC();
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
cld()
void nes::cpu_6502::cld (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 762 of file cpu_6502.cpp.
References clearD(), cycles, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xD8
         cpu->clearD();
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
clearC()
void nes::cpu_6502::clearC () private
Definition at line 99 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), clc(), cmp_imm(), cpx_imm(), cpy_imm(), sbc_imm(), slo_abs(), and slo_zp().
     {
         status &= ~0x1;
     }
clearD()
void nes::cpu_6502::clearD () private
Definition at line 124 of file cpu_6502.cpp.
References status.
Referenced by cld().
     {
         status &= ~0x8;
     }
clearI()
void nes::cpu_6502::clearI () private
Definition at line 114 of file cpu_6502.cpp.
References status.
Referenced by cli().
     {
         status &= ~0x4;
     }
clearV()
void nes::cpu_6502::clearV () private
Definition at line 73 of file cpu_6502.cpp.
References status.
Referenced by clv().
     {
         status &= ~0x40;
     }
cli()
void nes::cpu_6502::cli (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 413 of file cpu_6502.cpp.
References clearI(), and cycles.
Referenced by cpu_6502().
     {
         // 0x54
         cpu->clearI();
         cpu->cycles += 2;
     }
clv()
void nes::cpu_6502::clv (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 662 of file cpu_6502.cpp.
References clearV(), cycles, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xB8
         cpu->clearV();
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
cmp_imm()
void nes::cpu_6502::cmp_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 709 of file cpu_6502.cpp.
References A, clearC(), cycles, nes::opcode_t::imm, PC, setC(), setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xC9
         if(cpu->A >= op->imm) cpu->setC();
         else cpu->clearC();
         cpu->setZ(cpu->A - op->imm);
         cpu->setN(cpu->A - op->imm);
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
cpx_imm()
void nes::cpu_6502::cpx_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 770 of file cpu_6502.cpp.
References clearC(), cycles, nes::opcode_t::imm, PC, setC(), setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0xE0
         if(cpu->X >= op->imm) cpu->setC();
         else cpu->clearC();
         cpu->setZ(cpu->X - op->imm);
         uint8_t value = cpu->X - op->imm;
         cpu->setN(value);
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
cpy_imm()
void nes::cpu_6502::cpy_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 681 of file cpu_6502.cpp.
References clearC(), cycles, nes::opcode_t::imm, PC, setC(), setN(), setZ(), nes::opcode_t::sz, and Y.
Referenced by cpu_6502().
     {
         // 0xC0
         if(cpu->Y >= op->imm) cpu->setC();
         else cpu->clearC();
         cpu->setZ(cpu->Y - op->imm);
         cpu->setN(cpu->Y - op->imm);
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
dec_abs()
void nes::cpu_6502::dec_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 732 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0xCE
         uint8_t value = cpu->mapper->read_byte(op->imm);
         value -= 1;
         cpu->mapper->write_byte(op->imm, value);
         cpu->setZ(value);
         cpu->setN(value);
         cpu->cycles += 6;
         cpu->PC += op->sz;
     }
dec_zp()
void nes::cpu_6502::dec_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 694 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0xC6
         uint16_t addr = (0 << 8) | op->imm;
         uint8_t value = cpu->mapper->read_byte(addr);
         value -= 1;
         cpu->mapper->write_byte(addr, value);
         cpu->setZ(value);
         cpu->setN(value);
         cpu->cycles += 5;
         cpu->PC += op->sz;
     }
dex()
void nes::cpu_6502::dex (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 721 of file cpu_6502.cpp.
References cycles, PC, setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0xCA
         cpu->X--;
         cpu->setZ(cpu->X);
         cpu->setN(cpu->X);
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
dey()
void nes::cpu_6502::dey (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 502 of file cpu_6502.cpp.
References cycles, PC, setN(), setZ(), nes::opcode_t::sz, and Y.
Referenced by cpu_6502().
     {
         // 0x88
         cpu->Y--;
         cpu->setZ(cpu->Y);
         cpu->setN(cpu->Y);
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
eor_imm()
void nes::cpu_6502::eor_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 379 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, PC, setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x49
         cpu->A ^= op->imm;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 2;
     }
get_A()
uint8_t nes::cpu_6502::get_A ()
Definition at line 12 of file cpu_6502.cpp.
References A.
Referenced by nes::opcode_t::to_string().
     {
         return A;
     }
get_cycles()
uint32_t nes::cpu_6502::get_cycles ()
Definition at line 30 of file cpu_6502.cpp.
References cycles.
Referenced by MainWindow::MainWindow().
     {
         return cycles;
     }
get_PC()
uint16_t nes::cpu_6502::get_PC ()
Definition at line 7 of file cpu_6502.cpp.
References PC.
Referenced by not_implemented(), MemoryWindow::OnCPUStep(), MemoryWindow::OnCPUSteps(), and MainWindow::OnDebugROM().
     {
         return PC;
     }
get_state()
std::string nes::cpu_6502::get_state ()
Definition at line 22 of file cpu_6502.cpp.
References A, cycles, SP, status, X, and Y.
Referenced by step().
     {
         char message[1024];
         sprintf(message, "A:%.2X X:%.2X Y:%.2X P:%.2X SP:%.2X CYC:%3d",
                 A, X, Y, status, SP, (cycles * 3) % 341);
         return std::string(message);
     }
get_status()
uint8_t nes::cpu_6502::get_status ()
Definition at line 17 of file cpu_6502.cpp.
References status.
     {
         return status;
     }
jmp_abs()
void nes::cpu_6502::jmp_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 389 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, and PC.
Referenced by cpu_6502().
     {
         // 0x4C
         cpu->PC = op->imm;
         cpu->cycles += 3;
     }
jsr()
void nes::cpu_6502::jsr (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 257 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, PC, push8(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x20
         uint16_t addr = cpu->PC +  op->sz - 1;
         cpu->push8(addr & 0xFF);
         cpu->push8(addr >> 8);
         cpu->PC = op->imm;
         cpu->cycles += 6;
     }
lda_abs()
void nes::cpu_6502::lda_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 622 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xAA
         cpu->A = cpu->mapper->read_byte(op->imm);
         cpu->cycles += 2;
         if((cpu->PC >> 8) != (op->imm >>8)) cpu->cycles++;
         cpu->PC += op->sz;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
     }
lda_abs_x()
void nes::cpu_6502::lda_abs_x (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 670 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0xBD
         cpu->A = cpu->mapper->read_byte(op->imm + cpu->X);
         cpu->cycles += 2;
         if((cpu->PC >> 8) != (op->imm >>8)) cpu->cycles++;
         cpu->PC += op->sz;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
     }
lda_imm()
void nes::cpu_6502::lda_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 612 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, PC, setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xA9
         cpu->A = op->imm;
         cpu->cycles += 2;
         cpu->PC += op->sz;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
     }
lda_zp()
void nes::cpu_6502::lda_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 588 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xA5
         uint16_t addr = (0 << 8) | op->imm;
         cpu->A = cpu->mapper->read_byte(addr);
         cpu->cycles += 3;
         cpu->PC += op->sz;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
     }
lda_zp_x()
void nes::cpu_6502::lda_zp_x (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 650 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         uint16_t addr = (0 << 8) | op->imm;
         addr += cpu->X;
         cpu->A = cpu->mapper->read_byte(addr);
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 4;
     }
ldx_imm()
void nes::cpu_6502::ldx_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 578 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, PC, setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0xA2
         cpu->X = op->imm;
         cpu->cycles += 2;
         cpu->PC += op->sz;
         cpu->setZ(cpu->X);
         cpu->setN(cpu->X);
     }
ldx_zp()
void nes::cpu_6502::ldx_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 600 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setN(), setZ(), nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0xA6
         uint16_t addr = (0 << 8) | op->imm;
         cpu->X = cpu->mapper->read_byte(addr);
         cpu->cycles += 3;
         cpu->PC += op->sz;
         cpu->setZ(cpu->X);
         cpu->setN(cpu->X);
     }
ldy_imm()
void nes::cpu_6502::ldy_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 567 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, PC, setN(), setZ(), nes::opcode_t::sz, and Y.
Referenced by cpu_6502().
     {
         // 0xA0
         cpu->Y = op->imm;
         cpu->cycles += 2;
         cpu->PC += op->sz;
         cpu->setZ(cpu->Y);
         cpu->setN(cpu->Y);
     }
load_rom()
void nes::cpu_6502::load_rom (std::string filename)
Definition at line 911 of file cpu_6502.cpp.
References nes::NES_header::flag6, nes::NES_header::flag7, nes::ROM::get_header(), header, mapper, PC, ppu, nes::Mapper::read_byte(), rom, and status.
Referenced by MainWindow::MainWindow(), and MainWindow::OnOpenROM().
     {
         this->status = 0x34;
         try
         {
             rom = new nes::ROM(filename);
         }
         catch(std::string e)
         {
             throw e;
         }
         header = rom->get_header();
         uint8_t mapper_id = header.flag7 & 0xF0;
         mapper_id += header.flag6 >> 4;
         switch(mapper_id)
         {
             case 0:
                 mapper = new nes::Mapper0(rom, ppu);
                 break;
             default:
                 std::string message = "Unsupported mapper " + mapper_id;
                 throw message;
                 break;
         }
         PC = (mapper->read_byte(0xFFFD) << 8) | mapper->read_byte(0xFFFC);
 //        PC = 0xC000;
     }
nmi()
void nes::cpu_6502::nmi ()
Definition at line 136 of file cpu_6502.cpp.
References mapper, PC, push8(), nes::Mapper::read_byte(), setI(), and status.
Referenced by nes::PPU::step().
     {
         this->push8(this->PC >> 8);
         this->push8(this->PC & 0xFF);
         uint8_t status = this->status;
         status &= ~0x10;
         status &= ~0x20;
         this->push8(status);
         uint8_t pcl = this->mapper->read_byte(0xFFFA);
         this->setI();
         uint8_t pch = this->mapper->read_byte(0xFFFB);
         this->PC = (pch << 8) | pcl;
     }
nop_ea()
void nes::cpu_6502::nop_ea (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 785 of file cpu_6502.cpp.
References cycles, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xEA
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
nop_zp_F4()
void nes::cpu_6502::nop_zp_F4 (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 827 of file cpu_6502.cpp.
References cycles, PC, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xF4
         cpu->cycles += 4;
         cpu->PC += op->sz;
     }
not_implemented()
void nes::cpu_6502::not_implemented (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 129 of file cpu_6502.cpp.
References get_PC(), and nes::opcode_t::to_string().
Referenced by cpu_6502().
     {
         char message[1024];
         sprintf(message, "%.4X %s\n", cpu->get_PC(), op->to_string().c_str());
         throw std::string(message);
     }
ora_imm()
void nes::cpu_6502::ora_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 203 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, PC, setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x09
         cpu->A |= op->imm;
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 2;
     }
pha()
void nes::cpu_6502::pha (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 371 of file cpu_6502.cpp.
References A, cycles, PC, push8(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x48
         cpu->push8(cpu->A);
         cpu->cycles += 3;
         cpu->PC += op->sz;
     }
php()
void nes::cpu_6502::php (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 193 of file cpu_6502.cpp.
References cycles, PC, push8(), status, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x08
         uint8_t status = cpu->status;
         status |= 0x10;
         cpu->push8(status);
         cpu->PC += op->sz;
         cpu->cycles += 3;
     }
pla()
void nes::cpu_6502::pla (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 430 of file cpu_6502.cpp.
References A, cycles, PC, pop8(), setN(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x68
         cpu->A = cpu->pop8();
         cpu->setZ(cpu->A);
         cpu->setN(cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 4;
     }
plp()
void nes::cpu_6502::plp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 299 of file cpu_6502.cpp.
References cycles, PC, pop8(), status, and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x28
         uint8_t status = cpu->pop8();
         status &= ~0x10;
         status |= 0x20;
         cpu->status = status;
         cpu->cycles += 4;
         cpu->PC += op->sz;
     }
pop16()
uint16_t nes::cpu_6502::pop16 () private
pop8()
uint8_t nes::cpu_6502::pop8 () private
Definition at line 42 of file cpu_6502.cpp.
References mapper, nes::Mapper::read_byte(), and SP.
Referenced by pla(), plp(), rti(), and rts().
     {
         if(SP == 0xFF) SP = 0;
         else SP++;
         uint8_t value = mapper->read_byte(SP + 0x100);
         return value;
     }
push16()
void nes::cpu_6502::push16 (uint16_t value) private
push8()
void nes::cpu_6502::push8 (uint8_t value) private
Definition at line 35 of file cpu_6502.cpp.
References mapper, SP, and nes::Mapper::write_byte().
Referenced by brk(), jsr(), nmi(), pha(), and php().
     {
         mapper->write_byte(SP + 0x100, value);
         if(SP == 0) SP = 0xFF;
         else SP--;
     }
rla_zp_x()
void nes::cpu_6502::rla_zp_x (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 337 of file cpu_6502.cpp.
References nes::opcode_t::imm, and X.
     {
         // 0x37
         uint16_t addr = (0 << 8) | op->imm;
         addr += cpu->X;
 //        uint8_t data = cpu->mapper->read_byte(addr);
     }
rti()
void nes::cpu_6502::rti (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 355 of file cpu_6502.cpp.
References cycles, PC, pop8(), and status.
Referenced by cpu_6502().
     {
         // 0x40
         cpu->cycles += 6;
         uint8_t status = cpu->pop8();
         status &= ~0x10;
         cpu->status = status;
         cpu->PC = cpu->pop8();
         cpu->PC |= (cpu->pop8() << 8);
         char message[1024];
         sprintf(message, "PC: $%.4X   P: $%.2X", cpu->PC, cpu->status);
 //        throw std::string(message);
     }
rts()
void nes::cpu_6502::rts (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 420 of file cpu_6502.cpp.
References cycles, PC, and pop8().
Referenced by cpu_6502().
     {
         // 0x60
         uint16_t addr = (cpu->pop8() << 8);
         addr |= cpu->pop8();
         cpu->PC = addr + 1;
         cpu->cycles += 6;
     }
sbc_imm()
void nes::cpu_6502::sbc_imm (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 792 of file cpu_6502.cpp.
References A, checkC(), clearC(), cycles, nes::opcode_t::imm, PC, setC(), setN(), setV(), setZ(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xE9
         uint16_t temp = cpu->A + ~op->imm + cpu->checkC();
         uint8_t v = ~(cpu->A ^ op->imm) & (cpu->A ^ temp) & 0x80 ? 0xFF : 0x00;
         cpu->setV(v);
         cpu->setC();
         if(temp > 0xFF) cpu->clearC();
         cpu->A = temp & 0xFF;
         cpu->setZ(cpu->A);
         cpu->setN(temp);
         cpu->PC += op->sz;
         cpu->cycles += 2;
     }
sec()
void nes::cpu_6502::sec (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 347 of file cpu_6502.cpp.
References cycles, PC, setC(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x38
         cpu->setC();
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
sed()
void nes::cpu_6502::sed (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 834 of file cpu_6502.cpp.
References cycles, PC, setD(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0xF8
         cpu->setD();
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
sei()
void nes::cpu_6502::sei (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 476 of file cpu_6502.cpp.
References cycles, PC, setI(), and nes::opcode_t::sz.
Referenced by cpu_6502().
     {
         // 0x78
         cpu->cycles += 2;
         cpu->PC += op->sz;
         cpu->setI();
     }
setC()
void nes::cpu_6502::setC () private
Definition at line 94 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), cmp_imm(), cpx_imm(), cpy_imm(), sbc_imm(), sec(), slo_abs(), and slo_zp().
     {
         status |= 0x1;
     }
setD()
void nes::cpu_6502::setD () private
Definition at line 119 of file cpu_6502.cpp.
References status.
Referenced by sed().
     {
         status |= 0x8;
     }
setI()
void nes::cpu_6502::setI () private
Definition at line 109 of file cpu_6502.cpp.
References status.
Referenced by brk(), nmi(), and sei().
     {
         status |= 0x4;
     }
setN()
void nes::cpu_6502::setN (uint8_t check) private
Definition at line 50 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), and_imm(), and_ind_x(), bit_zp(), cmp_imm(), cpx_imm(), cpy_imm(), dec_abs(), dec_zp(), dex(), dey(), eor_imm(), lda_abs(), lda_abs_x(), lda_imm(), lda_zp(), lda_zp_x(), ldx_imm(), ldx_zp(), ldy_imm(), ora_imm(), pla(), sbc_imm(), slo_abs(), and slo_zp().
     {
         if((check >> 7) & 1)
         {
             status |= 0x80;
         }
         else
         {
             status &= ~0x80;
         }
     }
setV()
void nes::cpu_6502::setV (uint8_t check) private
Definition at line 67 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), bit_zp(), and sbc_imm().
     {
         if((check >> 6) & 1) status |= 0x40;
         else status &= ~0x40;
     }
setZ()
void nes::cpu_6502::setZ (uint8_t check) private
Definition at line 83 of file cpu_6502.cpp.
References status.
Referenced by adc_imm(), and_imm(), and_ind_x(), bit_zp(), cmp_imm(), cpx_imm(), cpy_imm(), dec_abs(), dec_zp(), dex(), dey(), eor_imm(), lda_abs(), lda_abs_x(), lda_imm(), lda_zp(), lda_zp_x(), ldx_imm(), ldx_zp(), ldy_imm(), ora_imm(), pla(), sbc_imm(), slo_abs(), and slo_zp().
     {
         if(check == 0) status |= 0x2;
         else status &= ~0x2;
     }
slo_abs()
void nes::cpu_6502::slo_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 213 of file cpu_6502.cpp.
References A, clearC(), cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setC(), setN(), setZ(), nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0x0F
         uint8_t value = cpu->mapper->read_byte(op->imm);
         uint8_t carry_true = value & 0x80;
         value <<= 1;
         cpu->mapper->write_byte(op->imm, value);
         cpu->A |= value;
         cpu->setN(cpu->A);
         cpu->setZ(cpu->A);
         if(carry_true) cpu->setC();
         else cpu->clearC();
         cpu->PC += op->sz;
         cpu->cycles += 2;
     }
slo_zp()
void nes::cpu_6502::slo_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 172 of file cpu_6502.cpp.
References A, clearC(), cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), setC(), setN(), setZ(), nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0x07
         cpu->cycles += 5;
         cpu->PC += op->sz;
         uint16_t addr = (0 << 8) | op->imm;
         uint8_t value = cpu->mapper->read_byte(addr);
         uint8_t carry_true = value & 0x80;
         value <<= 1;
         cpu->mapper->write_byte(addr, value);
         cpu->A |= value;
         cpu->setN(cpu->A);
         cpu->setZ(cpu->A);
         if(carry_true) cpu->setC();
         else cpu->clearC();
     }
sta_abs()
void nes::cpu_6502::sta_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 513 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0x8D
         cpu->mapper->write_byte(op->imm, cpu->A);
         cpu->cycles += 4;
         cpu->PC += op->sz;
     }
sta_ind_y()
void nes::cpu_6502::sta_ind_y (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 546 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::Mapper::read_byte(), nes::opcode_t::sz, nes::Mapper::write_byte(), and Y.
Referenced by cpu_6502().
     {
         // 0x91
         uint16_t addr = (0 << 8) | ((op->imm + cpu->Y) & 0xFF);
         uint16_t t_addr = (cpu->mapper->read_byte(addr + 1) << 8) |
                           cpu->mapper->read_byte(addr);
         cpu->mapper->write_byte(t_addr, cpu->A);
         cpu->PC += op->sz;
         cpu->cycles += 6;
     }
sta_zp()
void nes::cpu_6502::sta_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 484 of file cpu_6502.cpp.
References A, cycles, nes::opcode_t::imm, mapper, PC, nes::opcode_t::sz, and nes::Mapper::write_byte().
Referenced by cpu_6502().
     {
         // 0x85
         uint16_t addr = (0 << 8) | (op->imm & 0xFF);
         cpu->mapper->write_byte(addr, cpu->A);
         cpu->cycles += 3;
         cpu->PC += op->sz;
     }
step()
std::string nes::cpu_6502::step ()
Definition at line 943 of file cpu_6502.cpp.
References cycles, get_state(), last_cycles, nes::opcode_t::opcode, opcode, PC, ppu, nes::PPU::step(), and nes::opcode_t::to_string().
Referenced by MainWindow::MainWindow(), MemoryWindow::OnCPUStep(), and MemoryWindow::OnCPUSteps().
     {
         opcode_t *op = new opcode_t(this, PC);
         char message[1024];
         sprintf(message, "%.4X %s", PC, op->to_string().c_str());
         std::string state = message + get_state();
         try
         {
             opcode[op->opcode](this, op);
         }
         catch(std::string e)
         {
             throw e;
         }
         this->ppu->step(this->cycles - this->last_cycles);
         this->last_cycles = this->cycles;
         return state;
     }
stx_abs()
void nes::cpu_6502::stx_abs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 521 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, mapper, PC, nes::opcode_t::sz, nes::Mapper::write_byte(), and X.
Referenced by cpu_6502().
     {
         // 0x8E
         cpu->mapper->write_byte(op->imm, cpu->X);
         cpu->cycles += 4;
         cpu->PC += op->sz;
     }
stx_zp()
void nes::cpu_6502::stx_zp (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 493 of file cpu_6502.cpp.
References cycles, nes::opcode_t::imm, mapper, PC, nes::opcode_t::sz, nes::Mapper::write_byte(), and X.
Referenced by cpu_6502().
     {
         // 0x86
         uint16_t addr = (0 << 8) | op->imm;
         cpu->mapper->write_byte(addr, cpu->X);
         cpu->cycles += 3;
         cpu->PC += op->sz;
     }
txs()
void nes::cpu_6502::txs (cpu_6502 * cpu, opcode_t * op) static private
Definition at line 559 of file cpu_6502.cpp.
References cycles, PC, SP, nes::opcode_t::sz, and X.
Referenced by cpu_6502().
     {
         // 0x9A
         cpu->SP = cpu->X;
         cpu->cycles += 2;
         cpu->PC += op->sz;
     }
Member Data Documentation
A
uint8_t nes::cpu_6502::A = 0 private
Definition at line 52 of file cpu_6502.h.
Referenced by adc_imm(), and_imm(), and_ind_x(), bit_zp(), cmp_imm(), eor_imm(), get_A(), get_state(), lda_abs(), lda_abs_x(), lda_imm(), lda_zp(), lda_zp_x(), ora_imm(), pha(), pla(), sbc_imm(), slo_abs(), slo_zp(), sta_abs(), sta_ind_y(), and sta_zp().
cycles
uint32_t nes::cpu_6502::cycles = 0 private
Definition at line 54 of file cpu_6502.h.
Referenced by adc_imm(), and_imm(), and_ind_x(), bcc(), bcs(), beq(), bit_zp(), bmi(), bne(), bpl(), brk(), bvc(), bvs(), clc(), cld(), cli(), clv(), cmp_imm(), cpx_imm(), cpy_imm(), dec_abs(), dec_zp(), dex(), dey(), eor_imm(), get_cycles(), get_state(), jmp_abs(), jsr(), lda_abs(), lda_abs_x(), lda_imm(), lda_zp(), lda_zp_x(), ldx_imm(), ldx_zp(), ldy_imm(), nop_ea(), nop_zp_F4(), ora_imm(), pha(), php(), pla(), plp(), rti(), rts(), sbc_imm(), sec(), sed(), sei(), slo_abs(), slo_zp(), sta_abs(), sta_ind_y(), sta_zp(), step(), stx_abs(), stx_zp(), and txs().
header
nes::NES_header nes::cpu_6502::header private
Definition at line 48 of file cpu_6502.h.
Referenced by load_rom().
last_cycles
uint32_t nes::cpu_6502::last_cycles = 0 private
Definition at line 54 of file cpu_6502.h.
Referenced by step().
mapper
Mapper* nes::cpu_6502::mapper
Definition at line 43 of file cpu_6502.h.
Referenced by and_ind_x(), bit_zp(), brk(), dec_abs(), dec_zp(), lda_abs(), lda_abs_x(), lda_zp(), lda_zp_x(), ldx_zp(), load_rom(), nmi(), nes::opcode_t::opcode_t(), pop8(), push8(), slo_abs(), slo_zp(), sta_abs(), sta_ind_y(), sta_zp(), stx_abs(), and stx_zp().
opcode
void(* nes::cpu_6502::opcode[0x100])(cpu_6502 *, opcode_t *) private
Definition at line 75 of file cpu_6502.h.
Referenced by cpu_6502(), nes::opcode_t::opcode_t(), step(), and nes::opcode_t::to_string().
PC
uint16_t nes::cpu_6502::PC = 0 private
Definition at line 53 of file cpu_6502.h.
Referenced by adc_imm(), and_imm(), and_ind_x(), bcc(), bcs(), beq(), bit_zp(), bmi(), bne(), bpl(), brk(), bvc(), bvs(), clc(), cld(), clv(), cmp_imm(), cpx_imm(), cpy_imm(), dec_abs(), dec_zp(), dex(), dey(), eor_imm(), get_PC(), jmp_abs(), jsr(), lda_abs(), lda_abs_x(), lda_imm(), lda_zp(), lda_zp_x(), ldx_imm(), ldx_zp(), ldy_imm(), load_rom(), nmi(), nop_ea(), nop_zp_F4(), ora_imm(), pha(), php(), pla(), plp(), rti(), rts(), sbc_imm(), sec(), sed(), sei(), slo_abs(), slo_zp(), sta_abs(), sta_ind_y(), sta_zp(), step(), stx_abs(), stx_zp(), and txs().
ppu
PPU* nes::cpu_6502::ppu = nullptr private
Definition at line 49 of file cpu_6502.h.
Referenced by cpu_6502(), load_rom(), and step().
rom
nes::ROM* nes::cpu_6502::rom = nullptr private
Make an NES class and move this there
Definition at line 47 of file cpu_6502.h.
Referenced by load_rom().
SP
uint8_t nes::cpu_6502::SP = 0xFD private
Definition at line 52 of file cpu_6502.h.
Referenced by get_state(), pop8(), push8(), and txs().
status
uint8_t nes::cpu_6502::status = 0x24 private
Definition at line 52 of file cpu_6502.h.
Referenced by brk(), checkC(), checkN(), checkV(), checkZ(), clearC(), clearD(), clearI(), clearV(), get_state(), get_status(), load_rom(), nmi(), php(), plp(), rti(), setC(), setD(), setI(), setN(), setV(), and setZ().
X
uint8_t nes::cpu_6502::X = 0 private
Definition at line 52 of file cpu_6502.h.
Referenced by and_ind_x(), cpx_imm(), dex(), get_state(), lda_abs_x(), lda_zp_x(), ldx_imm(), ldx_zp(), rla_zp_x(), stx_abs(), stx_zp(), and txs().
Y
uint8_t nes::cpu_6502::Y = 0 private
Definition at line 52 of file cpu_6502.h.
Referenced by cpy_imm(), dey(), get_state(), ldy_imm(), and sta_ind_y().
The documentation for this class was generated from the following files:
src/cpu_6502.h
src/cpu_6502.cpp