craziNES: nes::Mapper Class Reference
nes::Mapper Class Reference abstract
#include <mapper.h>
Public Member Functions
uint8_t read_byte (uint16_t addr)
void write_byte (uint16_t addr, uint8_t value)
Protected Member Functions
virtual memory_section get_section (uint16_t addr)=0
Protected Attributes
nes::ROM * rom = nullptr
Detailed Description
Definition at line 19 of file mapper.h.
Member Function Documentation
get_section()
virtual memory_section nes::Mapper::get_section (uint16_t addr) protected pure virtual
Implemented in nes::Mapper0.
Referenced by read_byte(), and write_byte().
read_byte()
uint8_t nes::Mapper::read_byte (uint16_t addr)
Definition at line 9 of file mapper.cpp.
References nes::memory_section::addr, get_section(), nes::memory_section::offset, nes::memory_section::ptr, and nes::memory_section::read_handler.
Referenced by nes::cpu_6502::and_ind_x(), nes::cpu_6502::bit_zp(), nes::cpu_6502::brk(), nes::cpu_6502::dec_abs(), nes::cpu_6502::dec_zp(), nes::cpu_6502::lda_abs(), nes::cpu_6502::lda_abs_x(), nes::cpu_6502::lda_zp(), nes::cpu_6502::lda_zp_x(), nes::cpu_6502::ldx_zp(), nes::cpu_6502::load_rom(), nes::cpu_6502::nmi(), nes::opcode_t::opcode_t(), nes::cpu_6502::pop8(), nes::cpu_6502::slo_abs(), nes::cpu_6502::slo_zp(), and nes::cpu_6502::sta_ind_y().
     {
         memory_section s;
         try
         {
             s = get_section(addr);
         }
         catch(std::string e)
         {
             throw e;
         }
         if(s.read_handler != nullptr)
         {
             uint8_t result;
             try
             {
                 result = s.read_handler(s.ptr, addr);
             }
             catch(std::string e)
             {
                 throw e;
             }
             return result;
         }
         uint8_t *p = (uint8_t *)s.ptr;
         return p[s.addr - s.offset];
     }
write_byte()
void nes::Mapper::write_byte (uint16_t addr, uint8_t value)
Definition at line 40 of file mapper.cpp.
References nes::memory_section::addr, get_section(), nes::memory_section::offset, nes::memory_section::ptr, and nes::memory_section::write_handler.
Referenced by nes::cpu_6502::dec_abs(), nes::cpu_6502::dec_zp(), nes::cpu_6502::push8(), nes::cpu_6502::slo_abs(), nes::cpu_6502::slo_zp(), nes::cpu_6502::sta_abs(), nes::cpu_6502::sta_ind_y(), nes::cpu_6502::sta_zp(), nes::cpu_6502::stx_abs(), and nes::cpu_6502::stx_zp().
     {
         nes::memory_section s;
         try
         {
             s = get_section(addr);
         }
         catch(std::string e)
         {
             throw e;
         }
         if(s.write_handler != nullptr)
         {
             try
             {
                 s.write_handler(s.ptr, addr, value);
             }
             catch(std::string e)
             {
                 throw e;
             }
             return;
         }
         uint8_t *p = (uint8_t *)s.ptr;
         p[s.addr - s.offset] = value;
     }
Member Data Documentation
rom
nes::ROM* nes::Mapper::rom = nullptr protected
Definition at line 26 of file mapper.h.
Referenced by nes::Mapper0::Mapper0().
The documentation for this class was generated from the following files:
src/mappers/mapper.h
src/mappers/mapper.cpp