craziNES: nes::opcode_t Class Reference
nes::opcode_t Class Reference
#include <cpu_6502.h>
Public Member Functions
opcode_t (nes::MMU *mmu, uint16_t addr)
std::string to_string ()
Public Attributes
uint32_t instruction = 0
uint8_t opcode = 0
uint16_t imm = 0
uint8_t sz = 1
Private Member Functions
void decode_instruction ()
Detailed Description
Definition at line 11 of file cpu_6502.h.
Constructor & Destructor Documentation
opcode_t()
nes::opcode_t::opcode_t (nes::MMU * mmu, uint16_t addr)
Definition at line 110 of file cpu_6502.cpp.
References AND_imm, BCC, BCS, BEQ, BIT_abs, BIT_zp, BNE, BPL, BVS, CLC, CLD, CMP_imm, CPX_imm, DEC_zp, DEX, DEY, INC_zp, INX, INY, JMP_abs, JSR, LDA_abs, LDA_abs_x, LDA_imm, LDA_zp, LDX_imm, LDX_zp, LDY_imm, LSR_acc, NOP_1A, NOP_3A, NOP_5A, NOP_7A, NOP_abs_0C, NOP_abs_1C, NOP_abs_5C, NOP_abs_7C, NOP_abs_DC, NOP_abs_FC, NOP_DA, NOP_EA, NOP_FA, NOP_imm_80, NOP_zp_04, NOP_zp_14, NOP_zp_34, NOP_zp_44, NOP_zp_54, NOP_zp_64, NOP_zp_74, NOP_zp_D4, NOP_zp_F4, nes::cpu_6502::opcode, ORA_zp, PHA, PHP, PLA, PLP, nes::MMU::read_byte(), RTS, SEC, SEI, nes::setup_opcode_size_matrix(), STA_abs, STA_zp, STX_abs, STX_zp, STY_abs, STY_zp_x, and TXS.
     {
         if(op_sz_matrix[JMP_abs] == 0) setup_opcode_size_matrix();
         opcode = mmu->read_byte(addr);
         sz = op_sz_matrix[opcode];
         instruction = opcode;
         switch(opcode)
         {
             case NOP_zp_04:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case ORA_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_abs_0C:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case PHP:
                 break;
             case NOP_zp_14:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case CLC:
                 break;
             case NOP_1A:
                 break;
             case NOP_abs_1C:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case BPL:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case JSR:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case BIT_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case PLP:
                 break;
             case AND_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case BIT_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case NOP_zp_34:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case SEC:
                 break;
             case NOP_3A:
                 break;
             case NOP_zp_44:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case PHA:
                 break;
             case LSR_acc:
                 break;
             case JMP_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case NOP_zp_54:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_5A:
                 break;
             case NOP_abs_5C:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case RTS:
                 break;
             case NOP_zp_64:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case PLA:
                 break;
             case BVS:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_zp_74:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case SEI:
                 break;
             case NOP_7A:
                 break;
             case NOP_abs_7C:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case NOP_imm_80:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case STY_zp_x:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case STA_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case STX_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case DEY:
                 break;
             case STY_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case STA_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case STX_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case TXS:
                 break;
             case BCC:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDY_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDA_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDX_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDX_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDA_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDA_abs:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case BCS:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case LDA_abs_x:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case DEC_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case INY:
                 break;
             case CMP_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case DEX:
                 break;
             case BNE:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_zp_D4:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case CLD:
                 break;
             case NOP_DA:
                 break;
             case NOP_abs_DC:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             case CPX_imm:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case INC_zp:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case INX:
                 break;
             case NOP_EA:
                 break;
             case BEQ:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_zp_F4:
                 imm = mmu->read_byte(addr + 1);
                 instruction = (opcode << 8) | imm;
                 break;
             case NOP_FA:
                 break;
             case NOP_abs_FC:
                 imm = (mmu->read_byte(addr + 2) << 8) | mmu->read_byte(addr + 1);
                 instruction = (opcode << 16) | imm;
                 break;
             default:
                 char message[1024];
                 sprintf(message, "Unknown opcode 0x%.2X", opcode);
                 throw std::string(message);
                 break;
         }
     }
Member Function Documentation
decode_instruction()
void nes::opcode_t::decode_instruction () private
to_string()
std::string nes::opcode_t::to_string ()
Definition at line 352 of file cpu_6502.cpp.
References AND_imm, BCC, BCS, BEQ, BIT_abs, BIT_zp, BNE, BPL, BVS, CLC, CLD, CMP_imm, CPX_imm, DEC_zp, DEX, DEY, INC_zp, INX, INY, JMP_abs, JSR, LDA_abs, LDA_abs_x, LDA_imm, LDA_zp, LDX_imm, LDX_zp, LDY_imm, LSR_acc, NOP_1A, NOP_3A, NOP_5A, NOP_7A, NOP_abs_0C, NOP_abs_1C, NOP_abs_5C, NOP_abs_7C, NOP_abs_DC, NOP_abs_FC, NOP_DA, NOP_EA, NOP_FA, NOP_imm_80, NOP_zp_04, NOP_zp_14, NOP_zp_34, NOP_zp_44, NOP_zp_54, NOP_zp_64, NOP_zp_74, NOP_zp_D4, NOP_zp_F4, nes::cpu_6502::opcode, ORA_zp, PHA, PHP, PLA, PLP, RTS, SEC, SEI, STA_abs, STA_zp, STX_abs, STX_zp, STY_abs, STY_zp_x, and TXS.
Referenced by nes::cpu_6502::not_implemented(), nes::cpu_6502::step(), and MemoryWindow::view().
     {
         char temp[1024];
         switch(opcode)
         {
             case NOP_zp_04:
                 sprintf(temp, "NOP(0x04) 0x%.2X, 0", imm);
                 break;
             case ORA_zp:
                 sprintf(temp, "ORA 0x%.2X, 0", imm);
                 break;
             case NOP_abs_0C:
                 sprintf(temp, "NOP(0x0C) 0x%.4X", imm);
                 break;
             case PHP:
                 sprintf(temp, "PHP");
                 break;
             case NOP_zp_14:
                 sprintf(temp, "NOP(0x14) 0x%.2X, 0", imm);
                 break;
             case CLC:
                 sprintf(temp, "CLC");
                 break;
             case NOP_1A:
                 sprintf(temp, "NOP(0x1A)");
                 break;
             case NOP_abs_1C:
                 sprintf(temp, "NOP(0x1C) 0x%.2X", imm);
                 break;
             case BPL:
                 sprintf(temp, "BPL #0x%.2X", imm);
                 break;
             case JSR:
                 sprintf(temp, "JSR 0x%.4X", imm);
                 break;
             case BIT_zp:
                 sprintf(temp, "BIT 0x%.2X", imm);
                 break;
             case PLP:
                 sprintf(temp, "PLP");
                 break;
             case AND_imm:
                 sprintf(temp, "AND #0x%.2X", imm);
                 break;
             case BIT_abs:
                 sprintf(temp, "BIT 0x%.4X", imm);
                 break;
             case NOP_zp_34:
                 sprintf(temp, "NOP(0x34) 0x%.2X, 0", imm);
                 break;
             case SEC:
                 sprintf(temp, "SEC");
                 break;
             case NOP_3A:
                 sprintf(temp, "NOP(0x3A)");
                 break;
             case NOP_zp_44:
                 sprintf(temp, "NOP(0x44) 0x%.2X, 0", imm);
                 break;
             case PHA:
                 sprintf(temp, "PHA");
                 break;
             case LSR_acc:
                 sprintf(temp, "LSR accumulator");
                 break;
             case JMP_abs:
                 sprintf(temp, "JMP 0x%.4X", imm);
                 break;
             case NOP_zp_54:
                 sprintf(temp, "NOP(0x54) 0x%.2X, 0", imm);
                 break;
             case NOP_5A:
                 sprintf(temp, "NOP(0x5A)");
                 break;
             case NOP_abs_5C:
                 sprintf(temp, "NOP(0x5C) 0x%.4X, X", imm);
                 break;
             case RTS:
                 sprintf(temp, "RTS");
                 break;
             case NOP_zp_64:
                 sprintf(temp, "NOP(0x64) 0x%.2X, 0", imm);
                 break;
             case PLA:
                 sprintf(temp, "PLA");
                 break;
             case BVS:
                 sprintf(temp, "BVS 0x%.2X, 0", imm);
                 break;
             case NOP_zp_74:
                 sprintf(temp, "NOP(0x74) 0x%.2X, 0", imm);
                 break;
             case NOP_abs_7C:
                 sprintf(temp, "NOP(0x7C) 0x%.4X, X", imm);
                 break;
             case SEI:
                 sprintf(temp, "SEI");
                 break;
             case NOP_7A:
                 sprintf(temp, "NOP(0x7A)");
                 break;
             case NOP_imm_80:
                 sprintf(temp, "NOP(0x80) 0x%.2X, 0", imm);
                 break;
             case STY_zp_x:
                 sprintf(temp, "STY 0x%.2X, X", imm);
                 break;
             case STA_zp:
                 sprintf(temp, "STA 0x%.2X, 0", imm);
                 break;
             case STX_zp:
                 sprintf(temp, "STX 0x%.2X, 0", imm);
                 break;
             case DEY:
                 sprintf(temp, "DEY");
                 break;
             case STY_abs:
                 sprintf(temp, "STY 0x%.4X", imm);
                 break;
             case STA_abs:
                 sprintf(temp, "STA 0x%.4X", imm);
                 break;
             case STX_abs:
                 sprintf(temp, "STX 0x%.4X", imm);
                 break;
             case TXS:
                 sprintf(temp, "TXS");
                 break;
             case BCC:
                 sprintf(temp, "BCC 0x%.2X", imm);
                 break;
             case LDY_imm:
                 sprintf(temp, "LDY #0x%.2X", imm);
                 break;
             case LDX_imm:
                 sprintf(temp, "LDX #0x%.2X", imm);
                 break;
             case LDA_zp:
                 sprintf(temp, "LDA 0x%.2X, 0", imm);
                 break;
             case LDX_zp:
                 sprintf(temp, "LDX 0x%.2X, 0", imm);
                 break;
             case LDA_imm:
                 sprintf(temp, "LDA #0x%.2X", imm);
                 break;
             case LDA_abs:
                 sprintf(temp, "LDA 0x%.4X", imm);
                 break;
             case BCS:
                 sprintf(temp, "BCS 0x%.2X", imm);
                 break;
             case LDA_abs_x:
                 sprintf(temp, "LDA 0x%.4X, X", imm);
                 break;
             case DEC_zp:
                 sprintf(temp, "DEC 0x%.2X, 0", imm);
                 break;
             case INY:
                 sprintf(temp, "INY");
                 break;
             case CMP_imm:
                 sprintf(temp, "CMP #0x%.2X, 0", imm);
                 break;
             case DEX:
                 sprintf(temp, "DEX");
                 break;
             case BNE:
                 sprintf(temp, "BNE #0x%.2X", imm);
                 break;
             case NOP_zp_D4:
                 sprintf(temp, "NOP(0xD4) 0x%.2X, 0", imm);
                 break;
             case CLD:
                 sprintf(temp, "CLD");
                 break;
             case NOP_DA:
                 sprintf(temp, "NOP(0xDA)");
                 break;
             case NOP_abs_DC:
                 sprintf(temp, "NOP(0xDC) 0x%.4X, X", imm);
                 break;
             case CPX_imm:
                 sprintf(temp, "CPX #0x%.2X", imm);
                 break;
             case INC_zp:
                 sprintf(temp, "INC 0x%.2X, 0", imm);
                 break;
             case INX:
                 sprintf(temp, "INX");
                 break;
             case NOP_EA:
                 sprintf(temp, "NOP(0xEA)");
                 break;
             case BEQ:
                 sprintf(temp, "BEQ 0x%.2X, 0", imm);
                 break;
             case NOP_zp_F4:
                 sprintf(temp, "NOP(0xF4) 0x%.2X, 0", imm);
                 break;
             case NOP_FA:
                 sprintf(temp, "NOP(0xFA)");
                 break;
             case NOP_abs_FC:
                 sprintf(temp, "NOP(0xFC) 0x%.4X, X", imm);
                 break;
             default:
                 sprintf(temp, "Unknown opcode 0x%.2X", opcode);
                 break;
         }
         char message[1024];
         sprintf(message, "    %s", temp);
         return std::string(message);
     }
Member Data Documentation
imm
uint16_t nes::opcode_t::imm = 0
Definition at line 20 of file cpu_6502.h.
Referenced by nes::cpu_6502::jmp_abs(), nes::cpu_6502::ldx_imm(), nes::cpu_6502::stx_zp(), and MemoryWindow::view().
instruction
uint32_t nes::opcode_t::instruction = 0
Definition at line 18 of file cpu_6502.h.
opcode
uint8_t nes::opcode_t::opcode = 0
Definition at line 19 of file cpu_6502.h.
Referenced by nes::cpu_6502::step(), and MemoryWindow::view().
sz
uint8_t nes::opcode_t::sz = 1
Definition at line 21 of file cpu_6502.h.
Referenced by MemoryWindow::view().
The documentation for this class was generated from the following files:
include/cpu_6502.h
src/cpu_6502.cpp