craziNES: MemoryWindow Class Reference
MemoryWindow Class Reference
#include <debug.h>
Public Member Functions
MemoryWindow (wxWindow *parent, const wxString &title, const wxPoint &pos, const wxSize &size)
~MemoryWindow ()
void view (uint16_t start_addr, uint16_t end_addr)
void OnCPUStep (wxCommandEvent &event)
void OnCPUSteps (wxCommandEvent &event)
wxDECLARE_EVENT_TABLE ()
Public Attributes
wxListBox * memory_listbox = NULL
wxTextCtrl * debugger_pc = NULL
wxButton * cpu_step = NULL
wxTextCtrl * cpu_steps_count = NULL
wxButton * cpu_steps = NULL
Private Attributes
uint16_t start_addr = 0
uint16_t end_addr = 0
Detailed Description
Definition at line 26 of file debug.h.
Constructor & Destructor Documentation
MemoryWindow()
MemoryWindow::MemoryWindow (wxWindow * parent, const wxString & title, const wxPoint & pos, const wxSize & size)
Definition at line 117 of file debug.cpp.
         : wxFrame(parent, wxID_ANY, title, pos, size)
 {
 }
~MemoryWindow()
MemoryWindow::~MemoryWindow ()
Definition at line 122 of file debug.cpp.
 {
     wxGetApp().memory = NULL;
 }
Member Function Documentation
OnCPUStep()
void MemoryWindow::OnCPUStep (wxCommandEvent & event)
Definition at line 127 of file debug.cpp.
References cpu, debugger_pc, end_addr, nes::cpu_6502::get_PC(), open_registers(), start_addr, nes::cpu_6502::step(), and view().
 {
     if(wxGetApp().registers != NULL) open_registers();
     std::string status;
     try
     {
         status = cpu->step();
     }
     catch(std::string e)
     {
         std::cout << e << std::endl;
     }
     if(wxGetApp().log) wxGetApp().log->log_listbox->Append(status);
     std::cout << status << std::endl;
     view(start_addr, end_addr);
     char message[1024];
     sprintf(message, "0x%.4X", cpu->get_PC());
     debugger_pc->Clear();
     debugger_pc->AppendText(message);
 }
OnCPUSteps()
void MemoryWindow::OnCPUSteps (wxCommandEvent & event)
Definition at line 149 of file debug.cpp.
References cpu, debugger_pc, end_addr, nes::cpu_6502::get_PC(), open_registers(), start_addr, nes::cpu_6502::step(), and view().
 {
     if(wxGetApp().registers != NULL) open_registers();
     std::string steps_str = wxGetApp().memory->cpu_steps_count->GetValue().ToStdString();
     uint64_t steps = atoi(steps_str.c_str());
     std::string status;
     while(steps--)
     {
         try
         {
             status = cpu->step();
         }
         catch(std::string e)
         {
             std::cout << e << std::endl;
         }
         if(wxGetApp().log) wxGetApp().log->log_listbox->Append(status);
         std::cout << status << std::endl;
     }
     view(start_addr, end_addr);
     char message[1024];
     sprintf(message, "0x%.4X", cpu->get_PC());
     debugger_pc->Clear();
     debugger_pc->AppendText(message);
 }
view()
void MemoryWindow::view (uint16_t start_addr, uint16_t end_addr)
Definition at line 47 of file debug.cpp.
References cpu, debugger_pc, end_addr, nes::opcode_t::imm, memory_listbox, nes::opcode_t::opcode, start_addr, nes::opcode_t::sz, and nes::opcode_t::to_string().
Referenced by OnCPUStep(), and OnCPUSteps().
 {
     char message[1024];
     std::string msg;
     uint16_t addr = start_addr;
     this->start_addr = start_addr;
     this->end_addr = end_addr;
     sprintf(message, "0x%.4X", addr);
     debugger_pc->Clear();
     debugger_pc->AppendText(message);
     memory_listbox->Clear();
     nes::opcode_t *op;
     while(addr < end_addr)
     {
         try
         {
             op = new nes::opcode_t(cpu, addr);
             if(op->sz == 1) sprintf(message, "%.4X    %.2X      ", addr, op->opcode);
             if(op->sz == 2) sprintf(message, "%.4X    %.2X %.2X   ", addr, op->opcode, op->imm & 0xFF);
             if(op->sz == 3) sprintf(message, "%.4X    %.2X %.2X %.2X", addr, op->opcode, op->imm >> 8, op->imm & 0xFF);
             addr += op->sz;
             msg = message + op->to_string();
             delete op;
             memory_listbox->Append(msg.c_str());
         }
         catch(std::string e)
         {
             memory_listbox->Append(e.c_str());
             return;
         }
     }
 }
wxDECLARE_EVENT_TABLE()
MemoryWindow::wxDECLARE_EVENT_TABLE ()
Member Data Documentation
cpu_step
wxButton* MemoryWindow::cpu_step = NULL
Definition at line 36 of file debug.h.
cpu_steps
wxButton* MemoryWindow::cpu_steps = NULL
Definition at line 39 of file debug.h.
cpu_steps_count
wxTextCtrl* MemoryWindow::cpu_steps_count = NULL
Definition at line 38 of file debug.h.
debugger_pc
wxTextCtrl* MemoryWindow::debugger_pc = NULL
Definition at line 35 of file debug.h.
Referenced by OnCPUStep(), OnCPUSteps(), and view().
end_addr
uint16_t MemoryWindow::end_addr = 0 private
Definition at line 29 of file debug.h.
Referenced by OnCPUStep(), OnCPUSteps(), and view().
memory_listbox
wxListBox* MemoryWindow::memory_listbox = NULL
Definition at line 33 of file debug.h.
Referenced by view().
start_addr
uint16_t MemoryWindow::start_addr = 0 private
Definition at line 29 of file debug.h.
Referenced by OnCPUStep(), OnCPUSteps(), and view().
The documentation for this class was generated from the following files:
src/debug.h
src/debug.cpp