craziNES: src/debug.h File Reference
debug.h File Reference
#include <wx/wx.h>
Classes
class LogWindow
class RegistersWindow
class MemoryWindow
Enumerations
enum { BUTTON_cpu_step = 20, BUTTON_cpu_steps = 21 }
Functions
void open_memory ()
void open_registers ()
void open_log ()
Variables
const int ID_MEMORY_LISTBOX = 100
const int ID_REGISTERS_LISTBOX = 101
const int ID_CPU_STEP_COUNT = 102
const int ID_DEBUGGER_PC = 103
const int ID_LOG_LISTBOX = 104
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BUTTON_cpu_step
BUTTON_cpu_steps
Definition at line 44 of file debug.h.
 {
     BUTTON_cpu_step = 20,
     BUTTON_cpu_steps = 21
 };
Function Documentation
open_log()
void open_log ()
Definition at line 87 of file debug.cpp.
References ID_LOG_LISTBOX.
Referenced by MainWindow::OnDebugLog().
 {
     if(!wxGetApp().log)
     {
         wxGetApp().log = new LogWindow(wxGetApp().frame,
                               "Log", wxPoint(150, 50), wxSize(700, 480));
     }
     wxGetApp().log->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().log->Show(true);
     wxGetApp().log->log_listbox = new wxListBox(wxGetApp().log, ID_LOG_LISTBOX,
       wxPoint(20, 30), wxSize(550, 380));
     wxFont log_font(wxFontInfo(12).FaceName("Courier"));
     wxGetApp().log->log_listbox->SetFont(log_font);
 }
open_memory()
void open_memory ()
Definition at line 13 of file debug.cpp.
References BUTTON_cpu_step, BUTTON_cpu_steps, ID_CPU_STEP_COUNT, ID_DEBUGGER_PC, and ID_MEMORY_LISTBOX.
Referenced by MainWindow::OnDebugROM().
 {
     if(!wxGetApp().memory)
     {
         wxGetApp().memory = new MemoryWindow(wxGetApp().frame,
                               "NES memory", wxPoint(150, 50), wxSize(700, 480));
     }
     wxGetApp().memory->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().memory->Show(true);
     wxFont font(wxFontInfo(11).Bold());
     wxStaticText *label_memory_address = new wxStaticText(wxGetApp().memory,
                             wxID_ANY, wxT("Address    Data"), wxPoint(20, 5));
     label_memory_address->SetFont(font);
     wxFont mem_font(wxFontInfo(12).FaceName("Courier"));
     wxGetApp().memory->memory_listbox = new wxListBox(wxGetApp().memory, ID_MEMORY_LISTBOX,
       wxPoint(20, 30), wxSize(550, 380));
     wxGetApp().memory->memory_listbox->SetFont(mem_font);
     wxGetApp().memory->debugger_pc = new wxTextCtrl(wxGetApp().memory, ID_DEBUGGER_PC, "0x0000 0000",
                                                           wxPoint(580, 30), wxSize(90, 25), 0);
     wxGetApp().memory->cpu_step = new wxButton(wxGetApp().memory, BUTTON_cpu_step, _T("Step"),
                                                  wxPoint(580, 60), wxDefaultSize, 0);
     wxGetApp().memory->cpu_steps_count = new wxTextCtrl(wxGetApp().memory, ID_CPU_STEP_COUNT, "2",
                                                           wxPoint(580, 110), wxSize(90, 25), 0);
     wxGetApp().memory->cpu_steps = new wxButton(wxGetApp().memory, BUTTON_cpu_steps, _T("Multi-step"),
                                                   wxPoint(580, 140), wxDefaultSize, 0);
 }
open_registers()
void open_registers ()
Definition at line 104 of file debug.cpp.
Referenced by MemoryWindow::OnCPUStep(), MemoryWindow::OnCPUSteps(), and MainWindow::OnDebugRegisters().
 {
     if(!wxGetApp().registers)
     {
         wxGetApp().registers = new RegistersWindow(wxGetApp().frame,
                               "6502 Registers", wxPoint(150, 50), wxSize(700, 480));
     }
     wxGetApp().registers->SetBackgroundColour(wxColour(*wxWHITE));
     wxGetApp().registers->Show(true);
 }
Variable Documentation
ID_CPU_STEP_COUNT
const int ID_CPU_STEP_COUNT = 102
Definition at line 52 of file debug.h.
Referenced by open_memory().
ID_DEBUGGER_PC
const int ID_DEBUGGER_PC = 103
Definition at line 53 of file debug.h.
Referenced by open_memory().
ID_LOG_LISTBOX
const int ID_LOG_LISTBOX = 104
Definition at line 54 of file debug.h.
Referenced by open_log().
ID_MEMORY_LISTBOX
const int ID_MEMORY_LISTBOX = 100
Definition at line 50 of file debug.h.
Referenced by open_memory().
ID_REGISTERS_LISTBOX
const int ID_REGISTERS_LISTBOX = 101
Definition at line 51 of file debug.h.